version: '3'
services:
  api:
    image: confusionflow/confusionflow:latest
    ports:
     - "5000:80"
    volumes:
     # specify the path to the logdir folder in file .env
     - ${CONFUSIONFLOW_LOGDIR}:/logs
  web:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    ports:
     - "8080:80"
    volumes:
     - ./build:/usr/share/nginx/html
    depends_on:
      - api
    links:
      - api
